# Generated by Django 2.2 on 2019-04-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KernelBlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
