# Generated by Django 2.2 on 2019-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KernelBlog', '0002_delete_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATA', models.CharField(max_length=1000)),
                ('CURRENTDATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
